/**
 * AI Smart Replies Component
 * Shows quick reply suggestions generated by AI
 */

'use client'

import * as React from 'react'
import { Sparkles, RefreshCw } from 'lucide-react'
import { Button } from '@/components/ui/button'
import type { Mail } from '@/app/mail/data'
import type { SmartRepliesResponse } from '@/lib/ai/types'

interface AISmartRepliesProps {
  mail: Mail
  onSelectReply: (text: string) => void
}

export function AISmartReplies({ mail, onSelectReply }: AISmartRepliesProps) {
  const [loading, setLoading] = React.useState(false)
  const [replies, setReplies] = React.useState<SmartRepliesResponse['data']['replies']>([])
  const [error, setError] = React.useState<string | null>(null)

  const generateReplies = React.useCallback(async () => {
    try {
      setLoading(true)
      setError(null)

      const response = await fetch('/api/ai/suggest/replies', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          from: mail.email,
          subject: mail.subject,
          body: mail.text || mail.snippet || '',
          count: 3,
        }),
      })

      const data = await response.json()

      if (!response.ok || !data.success) {
        throw new Error(data.error || 'Failed to generate replies')
      }

      setReplies(data.data.replies || [])
    } catch (err) {
      console.error('Smart replies error:', err)
      setError(err instanceof Error ? err.message : 'Failed to generate replies')
    } finally {
      setLoading(false)
    }
  }, [mail])

  // Auto-generate on mount
  React.useEffect(() => {
    generateReplies()
  }, [generateReplies])

  if (error) {
    return (
      <div className="flex items-center gap-2 p-3 bg-red-50 border-2 border-red-300 rounded text-sm text-red-700">
        <span>Failed to generate smart replies.</span>
        <Button
          variant="ghost"
          size="sm"
          onClick={generateReplies}
          className="h-6 px-2"
        >
          Retry
        </Button>
      </div>
    )
  }

  if (loading) {
    return (
      <div className="flex items-center gap-2 p-3 bg-paper-100 border-2 border-hatch-400 rounded">
        <Sparkles className="h-4 w-4 text-ink-700 animate-pulse" />
        <span className="text-sm text-ink-600">Generating smart replies...</span>
      </div>
    )
  }

  if (replies.length === 0) {
    return null
  }

  return (
    <div className="space-y-2 mb-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-ink-700" />
          <span className="text-sm font-semibold text-ink-700">Quick Replies:</span>
        </div>
        <Button
          variant="ghost"
          size="sm"
          onClick={generateReplies}
          className="h-6 px-2 text-xs"
        >
          <RefreshCw className="h-3 w-3 mr-1" />
          Regenerate
        </Button>
      </div>

      <div className="flex flex-wrap gap-2">
        {replies.map((reply, index) => (
          <button
            key={index}
            onClick={() => onSelectReply(reply.text)}
            className="group relative px-3 py-1.5 bg-paper-100 hover:bg-paper-200 border-2 border-hatch-400 rounded-full text-sm text-ink-700 transition-all hover:scale-105 paper-grain"
          >
            <span>{reply.text}</span>
            {reply.confidence && (
              <span className="ml-1.5 text-xs text-ink-500 opacity-0 group-hover:opacity-100 transition-opacity">
                ({Math.round(reply.confidence * 100)}%)
              </span>
            )}
          </button>
        ))}
      </div>
    </div>
  )
}
