name: Bug Report
description: File a bug report to help us improve Gyattmail
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the following information.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what went wrong
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected outcome
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what you observed
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Logs
      description: If applicable, add screenshots or console logs
      placeholder: Paste screenshots or logs here

  - type: dropdown
    id: provider
    attributes:
      label: Email Provider
      description: Which email provider are you using?
      options:
        - Gmail
        - Outlook
        - iCloud
        - Custom IMAP
        - Not applicable
    validations:
      required: true

  - type: dropdown
    id: ai-provider
    attributes:
      label: AI Provider (if AI-related)
      description: Which AI provider were you using when the bug occurred?
      options:
        - Not using AI
        - Google Gemini
        - OpenAI GPT
        - Anthropic Claude
        - OpenRouter

  - type: input
    id: version
    attributes:
      label: Gyattmail Version
      description: What version of Gyattmail are you running?
      placeholder: e.g., v1.1.0 or commit SHA
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS
        - Windows
        - Linux
        - Other
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might help

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I have included all relevant information above
          required: true
        - label: I am willing to submit a PR to fix this issue (optional)
          required: false
