name: Feature Request
description: Suggest a new feature or enhancement for Gyattmail
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: I've also thought about...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - Email Management
        - AI Features
        - User Interface
        - Search & Organization
        - Account Management
        - Settings & Configuration
        - Performance
        - Accessibility
        - Security
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (Your Opinion)
      description: How important is this feature to you?
      options:
        - Critical - I can't use Gyattmail without this
        - High - Significantly improves my workflow
        - Medium - Nice to have
        - Low - Small quality of life improvement
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case and how this feature would help you
      placeholder: |
        As a user who...
        I need to...
        So that I can...
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, screenshots from other apps, or visual examples
      placeholder: Paste images or links here

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, research, or references about the feature request here
      placeholder: Links to similar features in other apps, technical considerations, etc.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I have provided a clear description of the problem and solution
          required: true
        - label: I am willing to submit a PR to implement this feature (optional)
          required: false
